import { Product } from "./types";

export const categories = [
  { id: "toys", name: "玩具", icon: "🧸" },
  { id: "books", name: "图书", icon: "📚" },
  { id: "clothing", name: "童装", icon: "👕" },
  { id: "feeding", name: "喂养", icon: "🍼" },
  { id: "diapers", name: "纸尿裤", icon: "👶" },
  { id: "accessories", name: "用品", icon: "🎒" },
];

export const products: Product[] = [
  // 玩具类
  {
    id: "1",
    name: "乐高得宝系列 我的第一次拼插玩具",
    description: "适合1.5岁以上宝宝的乐高大颗粒积木，包含15个彩色积木，锻炼宝宝手眼协调能力和创造力。安全无毒，易清洗。",
    price: 199,
    originalPrice: 259,
    category: "toys",
    images: [
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800",
      "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800",
    ],
    stock: 50,
    ageRange: "1.5-5岁",
    brand: "LEGO",
    rating: 4.8,
    reviewCount: 328,
    featured: true,
    tags: ["益智", "早教", "安全"],
    specifications: {
      材质: "ABS塑料",
      包装尺寸: "26.2 x 21.2 x 9.4 cm",
      重量: "540g",
    },
  },
  {
    id: "2",
    name: "费雪海马安抚玩具",
    description: "经典安抚玩具，柔和的灯光和舒缓的音乐帮助宝宝入睡。可水洗，机洗友好。",
    price: 129,
    originalPrice: 169,
    category: "toys",
    images: [
      "https://images.unsplash.com/photo-1629276301820-0f3eedc29571?w=800",
    ],
    stock: 35,
    ageRange: "0-24个月",
    brand: "Fisher-Price",
    rating: 4.9,
    reviewCount: 1256,
    featured: true,
    tags: ["安抚", "助眠", "经典"],
    specifications: {
      材质: "超柔纤维",
      电池: "2节AA电池（已含）",
      重量: "280g",
    },
  },
  {
    id: "3",
    name: "澳贝多功能游戏桌 蒙特梭利教具",
    description: "蒙特梭利理念设计，包含6种游戏模式，锻炼宝宝精细动作、认知能力和手眼协调。可调节高度，陪伴宝宝成长。",
    price: 299,
    originalPrice: 399,
    category: "toys",
    images: [
      "https://images.unsplash.com/photo-1596464716786-c6a36749b5e8?w=800",
    ],
    stock: 20,
    ageRange: "6-36个月",
    brand: "AUBY",
    rating: 4.7,
    reviewCount: 189,
    featured: true,
    tags: ["蒙特梭利", "早教", "多功能"],
    specifications: {
      尺寸: "45 x 35 x 40 cm",
      重量: "2.5kg",
      材质: "优质实木+环保漆",
    },
  },
  {
    id: "4",
    name: "汇乐拖拉玩具小鸭子",
    description: "可爱的小鸭子造型，拉动时会有翅膀摆动和嘎嘎叫声，吸引宝宝学步。帮助宝宝练习走路和平衡能力。",
    price: 59,
    originalPrice: 79,
    category: "toys",
    images: [
      "https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=800",
    ],
    stock: 100,
    ageRange: "12-36个月",
    brand: "HUILE",
    rating: 4.6,
    reviewCount: 267,
    tags: ["学步", "声光", "可爱"],
    specifications: {
      尺寸: "18 x 13 x 16 cm",
      重量: "320g",
      材质: "ABS环保塑料",
    },
  },
  {
    id: "5",
    name: "Babycare感统训练球套装",
    description: "包含6个不同质感的球，帮助宝宝触觉发育和感统训练。软硬适中，安全无毒。",
    price: 89,
    originalPrice: 119,
    category: "toys",
    images: [
      "https://images.unsplash.com/photo-1615336764851-44d3d6c0d8c7?w=800",
    ],
    stock: 60,
    ageRange: "6个月以上",
    brand: "Babycare",
    rating: 4.5,
    reviewCount: 145,
    tags: ["感统训练", "触觉", "安全"],
    specifications: {
      规格: "6件套",
      材质: "食品级硅胶",
      重量: "450g",
    },
  },

  // 图书类
  {
    id: "6",
    name: "小熊宝宝绘本系列（全15册）",
    description: "日本经典绘本，培养宝宝良好生活习惯。画风可爱，故事温馨，适合亲子共读。厚纸板设计，撕不烂咬不坏。",
    price: 168,
    originalPrice: 228,
    category: "books",
    images: [
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800",
    ],
    stock: 80,
    ageRange: "0-3岁",
    brand: "连环画出版社",
    rating: 4.9,
    reviewCount: 2341,
    featured: true,
    tags: ["经典", "习惯养成", "亲子阅读"],
    specifications: {
      开本: "24开",
      页数: "每册20页",
      装帧: "纸板书",
    },
  },
  {
    id: "7",
    name: "好饿的毛毛虫（立体书）",
    description: "艾瑞·卡尔经典作品，立体设计让故事更生动。教会宝宝星期、数字、食物和自然变化。世界著名绘本。",
    price: 58,
    originalPrice: 78,
    category: "books",
    images: [
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800",
    ],
    stock: 120,
    ageRange: "2-6岁",
    brand: "明天出版社",
    rating: 4.8,
    reviewCount: 5678,
    featured: true,
    tags: ["经典", "立体书", "认知启蒙"],
    specifications: {
      开本: "16开",
      页数: "24页",
      装帧: "精装立体书",
    },
  },
  {
    id: "8",
    name: "猜猜我有多爱你",
    description: "经典爱的表达绘本，教会宝宝表达爱。温馨的画风，动人的故事，亲子必读绘本。",
    price: 35,
    originalPrice: 48,
    category: "books",
    images: [
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800",
    ],
    stock: 90,
    ageRange: "3-6岁",
    brand: "少年儿童出版社",
    rating: 4.7,
    reviewCount: 3421,
    tags: ["情感教育", "经典", "亲情"],
    specifications: {
      开本: "16开",
      页数: "32页",
      装帧: "平装",
    },
  },
  {
    id: "9",
    name: "DK儿童百科全书",
    description: "英国DK出版社出品，内容丰富权威，涵盖自然、科学、历史等方方面面。高清图片，适合学龄儿童。",
    price: 138,
    originalPrice: 198,
    category: "books",
    images: [
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800",
    ],
    stock: 45,
    ageRange: "6-12岁",
    brand: "中国大百科全书出版社",
    rating: 4.9,
    reviewCount: 892,
    featured: true,
    tags: ["百科", "科普", "高清图文"],
    specifications: {
      开本: "16开",
      页数: "304页",
      装帧: "精装",
    },
  },
  {
    id: "10",
    name: "点点点（互动绘本）",
    description: "法国童书经典，互动性超强，让宝宝参与其中。点点、摇摇、吹一吹，神奇的事情发生了！",
    price: 45,
    originalPrice: 58,
    category: "books",
    images: [
      "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800",
    ],
    stock: 70,
    ageRange: "2-5岁",
    brand: "21世纪出版社",
    rating: 4.8,
    reviewCount: 1678,
    tags: ["互动", "创意", "好玩"],
    specifications: {
      开本: "20开",
      页数: "48页",
      装帧: "精装",
    },
  },

  // 童装类
  {
    id: "11",
    name: "巴拉巴拉男童纯棉T恤 3件装",
    description: "100%纯棉材质，柔软亲肤，透气舒适。卡通印花，活泼可爱。3件装超值。",
    price: 99,
    originalPrice: 159,
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800",
    ],
    stock: 150,
    ageRange: "3-8岁",
    brand: "Balabala",
    rating: 4.7,
    reviewCount: 567,
    featured: true,
    tags: ["纯棉", "舒适", "多件装"],
    specifications: {
      材质: "100%棉",
      颜色: "3色可选",
      尺码: "90-140cm",
    },
  },
  {
    id: "12",
    name: "戴维贝女童连衣裙 纱裙公主裙",
    description: "精美公主裙，多层纱裙设计，蓬松飘逸。花朵装饰，美丽大方。适合生日、聚会等场合穿着。",
    price: 168,
    originalPrice: 258,
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800",
    ],
    stock: 60,
    ageRange: "3-10岁",
    brand: "David&Belle",
    rating: 4.8,
    reviewCount: 389,
    featured: true,
    tags: ["公主裙", "礼服", "精致"],
    specifications: {
      材质: "聚酯纤维+棉",
      颜色: "粉色/白色",
      尺码: "100-150cm",
    },
  },
  {
    id: "13",
    name: "Mini纯棉连体衣新生儿礼盒装",
    description: "新生儿必备连体衣，纯棉材质，柔软亲肤。按扣设计，方便更换尿布。礼盒装，送礼佳品。",
    price: 128,
    originalPrice: 188,
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
    ],
    stock: 90,
    ageRange: "0-6个月",
    brand: "Mini",
    rating: 4.9,
    reviewCount: 1234,
    featured: true,
    tags: ["新生儿", "纯棉", "礼盒装"],
    specifications: {
      材质: "100%有机棉",
      包装: "3件装礼盒",
      尺码: "59-73cm",
    },
  },
  {
    id: "14",
    name: "安奈儿童装防蚊裤",
    description: "宽松舒适，防蚊透气。加长裤脚保护宝宝小腿。弹力腰围，方便穿脱。",
    price: 59,
    originalPrice: 89,
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800",
    ],
    stock: 200,
    ageRange: "1-6岁",
    brand: "Annil",
    rating: 4.6,
    reviewCount: 876,
    tags: ["防蚊", "透气", "舒适"],
    specifications: {
      材质: "95%棉+5%氨纶",
      颜色: "多色可选",
      尺码: "80-120cm",
    },
  },

  // 喂养类
  {
    id: "15",
    name: "贝亲宽口径奶瓶 玻璃240ml",
    description: "宽口径设计，冲泡方便，易清洗。高品质硼硅玻璃，安全耐高温。自然实感奶嘴，宝宝易接受。",
    price: 89,
    originalPrice: 119,
    category: "feeding",
    images: [
      "https://images.unsplash.com/photo-1620231109648-302d04431752?w=800",
    ],
    stock: 180,
    ageRange: "0-6个月",
    brand: "Pigeon",
    rating: 4.8,
    reviewCount: 3456,
    featured: true,
    tags: ["宽口", "玻璃", "自然实感"],
    specifications: {
      容量: "240ml",
      材质: "高硼硅玻璃",
      奶嘴: "SS号硅胶奶嘴",
    },
  },
  {
    id: "16",
    name: "新安怡自然原生奶瓶 PESU 260ml",
    description: "专利防胀气气阀，减少宝宝吞咽空气。宽口径设计，易清洗。PESU材质，轻便耐摔。",
    price: 128,
    originalPrice: 168,
    category: "feeding",
    images: [
      "https://images.unsplash.com/photo-1595246140625-573b715d11dc?w=800",
    ],
    stock: 140,
    ageRange: "0-6个月",
    brand: "AVENT",
    rating: 4.7,
    reviewCount: 2189,
    featured: true,
    tags: ["防胀气", "PESU", "宽口"],
    specifications: {
      容量: "260ml",
      材质: "PESU",
      奶嘴: "自然原生奶嘴",
    },
  },
  {
    id: "17",
    name: "小皮辅食果泥 组合装",
    description: "100%有机水果，无添加糖、盐、水。真空锁鲜，保留营养。多种口味可选，宝宝第一口辅食。",
    price: 158,
    originalPrice: 198,
    category: "feeding",
    images: [
      "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800",
    ],
    stock: 85,
    ageRange: "6个月以上",
    brand: "Ella's Kitchen",
    rating: 4.9,
    reviewCount: 1567,
    featured: true,
    tags: ["有机", "无添加", "真空"],
    specifications: {
      规格: "90g x 6袋",
      口味: "混合装",
      保质期: "12个月",
    },
  },
  {
    id: "18",
    name: "NUK学习杯 带手柄180ml",
    description: "从奶瓶到水杯的过渡杯，宽口杯嘴，训练宝宝吸吮和吞咽能力。防漏盖设计，外出携带方便。",
    price: 59,
    originalPrice: 79,
    category: "feeding",
    images: [
      "https://images.unsplash.com/photo-1614100851879-cfd92d64ac44?w=800",
    ],
    stock: 110,
    ageRange: "6个月以上",
    brand: "NUK",
    rating: 4.6,
    reviewCount: 934,
    tags: ["学饮杯", "防漏", "带手柄"],
    specifications: {
      容量: "180ml",
      材质: "PP+硅胶",
      适用: "6个月+",
    },
  },

  // 纸尿裤类
  {
    id: "19",
    name: "帮宝适一级帮 纸尿裤 M64片",
    description: "3D瞬吸芯体，瞬吸锁水，整夜干爽。超柔透气，宝宝不红屁股。弹性腰围，贴合舒适。",
    price: 139,
    originalPrice: 179,
    category: "diapers",
    images: [
      "https://images.unsplash.com/photo-1598142296961-ef33192c5f9e?w=800",
    ],
    stock: 300,
    ageRange: "6-11kg",
    brand: "Pampers",
    rating: 4.8,
    reviewCount: 5678,
    featured: true,
    tags: ["瞬吸", "透气", "整夜干爽"],
    specifications: {
      型号: "M码",
      片数: "64片",
      适合体重: "6-11kg",
    },
  },
  {
    id: "20",
    name: "大王光羽纸尿裤 大号 L44片",
    description: "日本原装进口，极薄0.2cm，透气性极佳。含维生素E护肤成分，呵护宝宝娇嫩肌肤。超声波压花，柔软舒适。",
    price: 168,
    originalPrice: 218,
    category: "diapers",
    images: [
      "https://images.unsplash.com/photo-1629157282173-1c1d4c3c397e?w=800",
    ],
    stock: 200,
    ageRange: "9-14kg",
    brand: "Googn",
    rating: 4.9,
    reviewCount: 4231,
    featured: true,
    tags: ["进口", "超薄", "含维E"],
    specifications: {
      型号: "L码",
      片数: "44片",
      适合体重: "9-14kg",
      产地: "日本",
    },
  },
  {
    id: "21",
    name: "尤妮佳妈咪宝贝 云柔新生纸尿裤",
    description: "云柔棉柔感，如云朵般柔软。环抱式弹性腰围，贴合宝宝身形。快速吸收，保持干爽。",
    price: 99,
    originalPrice: 129,
    category: "diapers",
    images: [
      "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800",
    ],
    stock: 250,
    ageRange: "0-6个月",
    brand: "Mamypoko",
    rating: 4.7,
    reviewCount: 2134,
    tags: ["云柔", "新生儿", "环抱腰围"],
    specifications: {
      型号: "NB/S码",
      片数: "82片",
      适合体重: "0-8kg",
    },
  },
  {
    id: "22",
    name: "好奇小森林学步裤 XL38片",
    description: "学习自主如厕的拉拉裤，穿脱方便如小内裤。弹力腰围，宝宝自己能穿。吸水迅速，防漏侧边。",
    price: 128,
    originalPrice: 168,
    category: "diapers",
    images: [
      "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800",
    ],
    stock: 180,
    ageRange: "12-17kg",
    brand: "Huggies",
    rating: 4.6,
    reviewCount: 1765,
    tags: ["拉拉裤", "学步", "易穿脱"],
    specifications: {
      型号: "XL码",
      片数: "38片",
      适合体重: "12-17kg",
    },
  },

  // 用品类
  {
    id: "23",
    name: "美德乐吸奶器 丝韵翼",
    description: "双韵律吸乳模式，按摩+吸乳，舒适高效。超静音设计，夜间使用不吵醒宝宝。小巧便携，可充电使用。",
    price: 899,
    originalPrice: 1199,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1584565399503-6b56e2c20cf1?w=800",
    ],
    stock: 50,
    ageRange: "妈妈用品",
    brand: "Medela",
    rating: 4.8,
    reviewCount: 345,
    featured: true,
    tags: ["双韵律", "静音", "可充电"],
    specifications: {
      模式: "双韵律",
      电池: "充电锂电池",
      重量: "220g",
    },
  },
  {
    id: "24",
    name: "Babycare多功能婴儿推车",
    description: "一键收折，单手操作。360°万向轮，推行顺滑。可调节座椅，双向推行。适合0-3岁宝宝。",
    price: 899,
    originalPrice: 1299,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800",
    ],
    stock: 40,
    ageRange: "0-3岁",
    brand: "Babycare",
    rating: 4.7,
    reviewCount: 567,
    featured: true,
    tags: ["一键收折", "双向推行", "360°万向轮"],
    specifications: {
      净重: "7.5kg",
      承重: "25kg",
      展开: "82x52x105cm",
    },
  },
  {
    id: "25",
    name: "可优比婴儿床 多功能",
    description: "实木材质，安全环保。可调节床板高度，陪伴宝宝成长。可转换成游戏床，使用更长久。",
    price: 599,
    originalPrice: 899,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1545893835-abaa50cbe628?w=800",
    ],
    stock: 35,
    ageRange: "0-3岁",
    brand: "KUB",
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    tags: ["实木", "可调节", "多功能"],
    specifications: {
      材质: "新西兰松木",
      尺寸: "120x60x85cm",
      重量: "18kg",
    },
  },
  {
    id: "26",
    name: "好孩子婴儿安全座椅",
    description: "通过i-Size认证，安全有保障。ISOFIX接口，安装稳固。可调节头枕和靠背，陪伴宝宝成长。360°旋转，方便宝宝上下车。",
    price: 1299,
    originalPrice: 1699,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1589978237594-ec25f5b5d7a6?w=800",
    ],
    stock: 25,
    ageRange: "0-4岁",
    brand: "Goodbaby",
    rating: 4.9,
    reviewCount: 189,
    featured: true,
    tags: ["i-Size认证", "ISOFIX", "360°旋转"],
    specifications: {
      认证: "i-Size",
      体重: "0-18kg",
      安装: "ISOFIX+支撑腿",
    },
  },
  {
    id: "27",
    name: "美德乐储奶袋 180ml 50片装",
    description: "食品级材质，安全无毒。双层密封设计，防漏保鲜。可直立存放，节省空间。预写日期标签，方便记录。",
    price: 89,
    originalPrice: 109,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
    ],
    stock: 150,
    ageRange: "妈妈用品",
    brand: "Medela",
    rating: 4.7,
    reviewCount: 876,
    tags: ["食品级", "双层密封", "预写标签"],
    specifications: {
      容量: "180ml",
      包装: "50片装",
      材质: "食品级PE",
    },
  },
  {
    id: "28",
    name: "贝亲婴儿洗澡盆 新生儿可用",
    description: "人体工学设计，支持宝宝躺着洗。防滑底座，使用安全。可悬挂收纳，节省空间。适合0-3岁宝宝。",
    price: 79,
    originalPrice: 99,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1619551734325-81aaf323686c?w=800",
    ],
    stock: 120,
    ageRange: "0-3岁",
    brand: "Pigeon",
    rating: 4.6,
    reviewCount: 654,
    tags: ["人体工学", "防滑", "可悬挂"],
    specifications: {
      尺寸: "53x33x21cm",
      材质: "PP材质",
      适用: "0-3岁",
    },
  },
  {
    id: "29",
    name: "子初婴儿护臀膏",
    description: "含氧化锌和乳木果油，预防和缓解红屁股。温和配方，无香精无酒精。厚实质地，隔离刺激。",
    price: 49,
    originalPrice: 69,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800",
    ],
    stock: 200,
    ageRange: "0-3岁",
    brand: "Zichu",
    rating: 4.8,
    reviewCount: 1234,
    tags: ["护臀", "含氧化锌", "温和"],
    specifications: {
      规格: "50g",
      成分: "氧化锌5%",
      保质期: "3年",
    },
  },
  {
    id: "30",
    name: "婴儿口腔清洁指套牙刷",
    description: "食品级硅胶，安全可入口。柔软刷头，不伤牙龈。戴在手指上使用，方便控制。帮助宝宝建立口腔清洁习惯。",
    price: 29,
    originalPrice: 39,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1596899977502-72c316b0ff8d?w=800",
    ],
    stock: 300,
    ageRange: "0-2岁",
    brand: "Baby Smilo",
    rating: 4.5,
    reviewCount: 567,
    tags: ["食品级硅胶", "指套设计", "入门牙刷"],
    specifications: {
      材质: "食品级硅胶",
      包装: "2只装",
      适用: "0-2岁",
    },
  },
];

export const featuredProducts = products.filter((p) => p.featured);

export const getCategoryProducts = (category: string) =>
  products.filter((p) => p.category === category);

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);

export const getRelatedProducts = (productId: string, limit = 4) => {
  const product = getProductById(productId);
  if (!product) return [];

  return products
    .filter((p) => p.category === product.category && p.id !== productId)
    .slice(0, limit);
};
